baseurl = "https://iassistdata.org/"
title = "IASSIST - International Association for Social Science Information Service and Technology "
theme = "hugo-universal-theme"
#themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code: UA-56271826-1 / G-7MVEGR13V8
googleAnalytics = "G-7MVEGR13V8"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

# [[menu.main]]
#     name       = "Option 1: Default Page"
#     url        = "/"
#     weight     = 1
#     parent     = "menu.home"

# [[menu.main]]
#     name       = "Option 2: Application"
#     url        = "/"
#     weight     = 2
#     parent     = "menu.home"

[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    url        = "/img/logo-whitebg.jpg"
    weight     = 2

[[menu.main]]
    name       = "About IASSIST"
    identifier = "section.about"
    url        = "/about/"
    weight     = 1
    parent     = "menu.about"
    post       = 1

[[menu.main]]
    name       = "FAQ"
    identifier = "section.faq"
    url        = "/about/faq/"
    weight     = 100
    parent     = "menu.about"
    post       = 4
	
[[menu.main]]
    name       = "Officials"
    identifier = "section.officials"
    url        = "/about/officials/"
    weight     = 10
    parent     = "menu.about"
    post       = 2

[[menu.main]]
    name       = "Elections"
    identifier = "section.elections"
    url        = "/about/elections/"
    weight     = 90
    parent     = "menu.about"
    post       = 2
	
[[menu.main]]
    name       = "Committees and Groups"
    identifier = "section.committees-amd-groups"
    url        = "/about//"
    weight     = 30
    parent     = "menu.about"
    post       = 2
	
[[menu.main]]
    name       = "Fellows Program"
    identifier = "section.fellows-program"
    url        = "/about/fellows-program/"
    weight     = 40
    parent     = "menu.about"
    post       = 2
	
[[menu.main]]
    name       = "Brand, Promotion and Media"
    identifier = "section.media"
    url        = "/about/media/"
    weight     = 50
    parent     = "menu.about"
    post       = 2
	
[[menu.main]]
    name       = "Achievement Award"
    identifier = "section.achievement-award"
    url        = "/about/iassist-achievement-award/"
    weight     = 60
    parent     = "menu.about"
    post       = 2
	
[[menu.main]]
    name       = "Brand, Promotion and Media"
    identifier = "section.media"
    url        = "/about/media/"
    weight     = 70
    parent     = "menu.about"
    post       = 2
	
[[menu.main]]
    name       = "Documents (NEW)"
    identifier = "section.documents"
    url        = "/about/documents/"
    weight     = 80
    parent     = "menu.about"
    post       = 2

[[menu.main]]
    name       = "Events"
    identifier = "menu.events"
    url        = "/img/logo-whitebg.jpg"
    weight     = 2.5

[[menu.main]]
    name       = "Annual Conference"
    identifier = "section.annual-conference"
    url        = "/conferences/"
    weight     = 1
    parent     = "menu.events"
    post       = 1

	[[menu.main]]
    name       = "Webinars"
    identifier = "section.webinars"
    url        = "/community/webinars"
    weight     = 50
    parent     = "menu.events"
    post       = 2

	[[menu.main]]
    name       = "Africa Workshop"
    identifier = "section.africa-workshop"
    url        = "/#/"
    weight     = 100
    parent     = "menu.events"
    post       = 2
	
	[[menu.main]]
    name       = "Events Calendar"
    identifier = "section.events-calendar"
    url        = "/#/"
    weight     = 101
    parent     = "menu.events"
    post       = 2

[[menu.main]]
    name       = "IQ+iBlog"
    identifier = "menu.iq"
    url        = "/img/logo-whitebg.jpg"
    weight     = 2.7

[[menu.main]]
    name       = "IASSIST Quarterly"
    identifier = "section.iq"
    url        = "/#/"
    weight     = 1
    parent     = "menu.iq"
    post       = 1
	
[[menu.main]]
    name       = "iBlog"
    identifier = "section.iblog"
    url        = "/#/"
    weight     = 1
    parent     = "menu.iq"
    post       = 1
	
[[menu.main]]
    name       = "Membership"
    identifier = "menu.membership"
    url        = "/img/logo-whitebg.jpg"
    weight     = 2.9

[[menu.main]]
    name       = "Membership Benefits"
    identifier = "section.benefits"
    url        = "/#/"
    weight     = 1
    parent     = "menu.membership"
    post       = 1
	
[[menu.main]]
    name       = "Manage Your Membership"
    identifier = "section.benefits"
    url        = "/#/"
    weight     = 5
    parent     = "menu.membership"
    post       = 1

[[menu.main]]
    name       = "Jobs Repository"
    identifier = "section.jobs-repository"
    url        = "/#/"
    weight     = 10
    parent     = "menu.membership"
    post       = 1

[[menu.main]]
    name       = "Interest Groups"
    identifier = "section.interest-groups"
    url        = "/#/"
    weight     = 20
    parent     = "menu.membership"
    post       = 1

[[menu.main]]
    name       = "Discussion List"
    identifier = "section.discussion-list"
    url        = "/#/"
    weight     = 30
    parent     = "menu.membership"
    post       = 1

# [[menu.main]]
#     name       = "Accordions"
#     url        = ""
#     weight     = 1
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Alerts"
#     url        = ""
#     weight     = 2
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Buttons"
#     url        = ""
#     weight     = 3
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Content Boxes"
#     url        = ""
#     weight     = 4
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Horizontal Blocks"
#     url        = ""
#     weight     = 5
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Pagination"
#     url        = ""
#     weight     = 6
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Tabs"
#     url        = ""
#     weight     = 7
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Typography"
#     url        = ""
#     weight     = 8
#     parent     = "section.shortcodes"

# [[menu.main]]
#     name       = "Default Sticky Header"
#     url        = ""
#     weight     = 1
#     parent     = "section.headervariations"

# [[menu.main]]
#     name       = "No Sticky Header"
#     url        = ""
#     weight     = 2
#     parent     = "section.headervariations"

# [[menu.main]]
#     name       = "Light Header"
#     url        = ""
#     weight     = 3
#     parent     = "section.headervariations"

[[menu.main]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 5

[[menu.main]]
    identifier = "join-us"
    name       = "Join Us!"
    url        = "/contact/"
    weight     = 7

# Top bar social links menu

#[[menu.topbar]]
#    weight = 1
#    name = "GitHub"
#    url = "https://github.com/devcows/hugo-universal-theme"
#    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com/iassistdata"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com/iassistdata"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

#[[menu.topbar]]
#    weight = 4
#    name = "Email"
#    url = "mailto:your@email.com"
#    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "IASSIST"
    defaultKeywords = ["research data", "association", "professional development", "data support", "data science", "community", "iassist quarterly"]
    mainSections = ["blog"]
    defaultDescription = "IASSIST is an international organization of professionals working in and with information technology and data services to support research and teaching in the social sciences and beyond."

    # Social media
    facebook_site = "iassistdata/" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "iassistdata" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "pink"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email (but does this work for Netlify as well?)
    email = "iassistwebmaster@gmail.com"
    contact_form_ajax = false

    about_us = "IASSIST is an international organization of professionals working in and with information technology and data services to support research and teaching in the social sciences and beyond"

    privacy_policy = """/about/privacy-policy/"""
    code_of_conduct = """/community/code-of-conduct/"""	
    
    copyright = "Content licensed under Creative Commons BY 4.0" 
    # Copyright (c) 2015 - 2016, YourCompany; all rights reserved.

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    
	address = """<p class=""><strong>IASSIST at your service</strong>
        <br /><a href="/about/officials/">&raquo; Contact Officials</a>
        <br /><a href="/about/become-a-member/">&raquo; Manage Membership</a>
        <br /><a href="/about/web-team/">&raquo; Contact Web Team</a>
        <br /><strong></strong>
      </p>
      """
    
	latitude = "44.9769102"
    longitude = "-93.2562968"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us: iassistwebmaster@gmail.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.
    # We have hacked this to feature some of our key services!
    title = "This is IASSIST"

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = ""

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "IASSIST Store"
    subtitle = "IASSIST branded products on Redbubble"
    link_url = "/about/media/"
    link_text = "To the store"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    # We have hacked this to feature our social media banners
    title = "IASSIST on Social Media"
    subtitle = "Follow us on various platforms and get the latest IASSIST or data services updates as they happen."

[params.recent_posts]
    enable = true
    title = "From iBlog"
    subtitle = "iBlog is IASSIST's own blog. Entries on various topics are written by our members."

[params.alerts]
    enable = false
    # Setting this to true prints alerts defined in their own files stacked on top of each other on the main page, below the carousel. 
    title = "Alerts"

[markup.goldmark.renderer]
    unsafe= true
